---
- name: Configure TOTP authentication for Cockpit
  hosts: all
  become: yes
  vars:
    ansible_ssh_port: "{{ some_ssh_int }}"
    ansible_become_pass: "{{ random_pass }}"
    cockpit_user: "{{ normal_user }}"
  
  tasks:

    - name: Add TOTP authentication to PAM configuration for Cockpit
      lineinfile:
        path: /etc/pam.d/cockpit
        line: |
          auth required pam_google_authenticator.so
          auth required pam_succeed_if.so user in [{{ cockpit_user }}]
        insertbefore: BOF

    - name: Restart Cockpit service
      systemd:
        name: cockpit.socket
        state: restarted

    # - name: Generate TOTP keys for the specified user
      # become_user: "{{ cockpit_user }}"
      # command: google-authenticator --quiet
      
    - name: Generate TOTP keys for the specified user
      expect:
        command: su -c "google-authenticator --quiet --time-based --disallow-reuse --no-rate-limit" "{{ cockpit_user }}"
        responses:
          Password: "{{ ansible_become_pass }}"
    # - name: Generate TOTP keys for the specified user
      # command: google-authenticator --quiet --time-based --disallow-reuse --no-rate-limit
      # become_user: "{{ cockpit_user }}"

  handlers:
    - name: Restart Cockpit service if PAM configuration changed
      systemd:
        name: cockpit.socket
        state: restarted
      listen: "PAM configuration changed"
