---
- name: Install necessary packages on Ubuntu 22.04 LTS
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install core packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - debian-goodies
        - openssh-server
        - cockpit
        - speedtest-cli
        - nfs-common
        - htop

    - name: Install Passlib via pip
      pip:
        name: passlib
        state: present