---
- name: Update Ubuntu servers and notify if reboot is required
  hosts: all
  become: yes  # This enables privilege escalation to root
  vars: 
    ansible_ssh_port: "{{ some_ssh_int }}"  # Change this to your custom SSH port
    ansible_become_pass: "{{ random_pass }}"  # Replace with your root password
    #notification_url: "{{ some_url }}"  # Replace with your notification endpoint
  tasks:
    - name: Set VA-API driver
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: '^LIBVA_DRIVER_NAME='
        line: LIBVA_DRIVER_NAME=iHD
    - name: Add cmdline default
      ansible.builtin.lineinfile:
        path: /etc/default/grub.d/cmdline_default.cfg
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet i915.enable_hangcheck=N intel_idle.preferred_cstates=2 nosmt mitigations=off transparent_hugepage=always"'
        mode: '644'
        state: present
        create: true
      notify:
        - Update grub
    - name: Install drivers
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - clinfo
          - vainfo
          - intel-media-va-driver-non-free
          - intel-gpu-tools
          - ocl-icd-libopencl1
          - intel-opencl-icd
          - firmware-linux-nonfree
          - libvpl2
          - onevpl-tools
  handlers:
    - name: Update grub
      ansible.builtin.command: update-grub
