---
- name: Update Ubuntu servers
  hosts: all
  become: yes  # This enables privilege escalation to root
  vars: 
    ansible_ssh_port: 22  # Change this to your custom SSH port
    ansible_become_pass: your_root_password_here  # Replace with your root password
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoclean: yes
