---
- name: Deleting defaultUser
  hosts: all
  become: yes
  become_user: root
  vars: 
    ansible_ssh_port: "{{ some_ssh_int }}"
    ansible_become_pass: "{{ random_pass }}"
    username: "{{ defaultUser }}"

  tasks:
    - name: Ensure the user exists before deletion
      command: id {{ username }}
      register: user_exists
      ignore_errors: yes

    - name: Delete the user if exists
      user:
        name: "{{ username }}"
        state: absent
        remove: yes
      when: user_exists.rc == 0
