---
- name: Install necessary packages on Ubuntu 22.04 LTS
  hosts: all
  become: yes
  vars:
    regular_user: "{{ some_user }}"
    devops_user: "{{ some_dev_user }}"
    new_password: "{{ random_pass }}"
    my_sweet_key: "{{ mykey }}"
    modded_user: "{{ the_user }}"
    new_ssh_port: "{{ some_ssh_int }}"
    ansible_ssh_port: "{{ some_ssh_int }}"
    ansible_become_pass: "{{ random_pass }}"
    username: "{{ defaultUser }}"
    other_user: "{{ normal_user }}"
    notification_url: "{{ some_url }}"
    
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install core packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - python3-requests
        - debian-goodies
        - openssh-server
        - cockpit
        - speedtest-cli
        - nfs-common
        - htop
        - neofetch

    - name: Install Passlib via pip
      pip:
        name: passlib
        state: present
        
#userAddition.yml