---
- name: Setup Timeshift for Automated Backups
  hosts: all
  become: yes
  become_user: root
  vars:
    ansible_ssh_port: "{{ some_ssh_int }}"
    ansible_become_pass: "{{ random_pass }}"
    regular_user: "{{ normal_user }}"  # User who owns the backup directory
    backup_dir: "/home/{{ regular_user }}/timeshift_backups"  # Directory for Timeshift snapshots
    backup_script: "/home/{{ regular_user }}/scripts/timeshift_backup.sh"  # Path to the backup script
    time_hour: "{{ cron_hour }}"
    time_minute: "{{ cron_minute }}"
    cron_time: "{{ time_minute }} {{ time_hour }} * * *"  # Cron schedule (daily)
    comment: "Daily HomeDocker_Server backup"  # Comment for Timeshift snapshots
    nfs_server: "{{ nas_ip }}"
    nfs_share: "{{ nas_dataset }}"
    mount_point: "{{ backup_dir }}"

  tasks:
    - name: Ensure Timeshift is installed
      apt:
        name: timeshift
        state: present
        update_cache: yes

    - name: Create timeshift backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: "{{ regular_user }}"
        group: "{{ regular_user }}"
        mode: "0755"

    - name: Ensure the mount point exists
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Add NFS mount entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^{{ nfs_server }}:{{ nfs_share }}'
        line: "{{ nfs_server }}:{{ nfs_share }} {{ mount_point }} nfs defaults 0 0"
        state: present
        backup: yes  # Optional: create a backup of fstab before modifying it

    - name: Mount the NFS share
      mount:
        name: "{{ mount_point }}"
        src: "{{ nfs_server }}:{{ nfs_share }}"
        fstype: nfs
        state: mounted
        opts: defaults

    - name: Configure Timeshift (without triggering a snapshot)
      command: timeshift --snapshot-device="{{ backup_dir }}" --type rsync --tags D --comments "Scheduled daily backup"
      register: timeshift_setup
      failed_when: "'Failed' in timeshift_setup.stderr"

    - name: Create Timeshift backup script
      copy:
        dest: "{{ backup_script }}"
        content: |
          #!/bin/bash
          # Trigger a Timeshift snapshot in RSYNC mode
          timeshift --create --snapshot-device="{{ backup_dir }}" --type rsync --comments "{{ comment }}" --tags D
        owner: root
        group: root
        mode: '0755'

    - name: Schedule daily backup with cron
      cron:
        name: "Daily Timeshift Backup"
        user: root
        minute: "{{ time_minute }}"
        hour: "{{ time_hour }}"
        job: "/bin/bash {{ backup_script }}"

    - name: Display success message
      debug:
        msg: "Timeshift setup complete! Snapshots will be created daily at {{ cron_time }} in {{ backup_dir }}."
